spring:
  profiles:
    active: dev

elasticsearch:
  index: news
  host: localhost
  port: 9200
  scheme: http

naver:
  request-url: https://openapi.naver.com/v1/search/news.json
  client-id:
  client-secret:

